"""On-disk session schema.

The libsignal protocol state (identity, prekeys, sessions, known peer
identities) lives inside an opaque bincode blob produced by
:class:`sigsig_libsignal._libsignal.SignalStore`. sigsig just carries it
alongside the user-facing account metadata.
"""

from __future__ import annotations

import base64
from typing import Annotated, Any, Self

from pydantic import BaseModel, BeforeValidator, ConfigDict, PlainSerializer

from sigsig.types import DeviceId

SCHEMA_VERSION = 2


def _b64_decode(value: Any) -> bytes:
    if isinstance(value, bytes):
        return value
    if isinstance(value, str):
        return base64.b64decode(value)
    raise TypeError(f"cannot decode {type(value).__name__} as bytes")


def _b64_encode(value: bytes) -> str:
    return base64.b64encode(value).decode("ascii")


B64Bytes = Annotated[
    bytes,
    BeforeValidator(_b64_decode),
    PlainSerializer(_b64_encode, return_type=str),
]


class SessionFile(BaseModel):
    """Top-level on-disk session schema.

    Sensitive fields (``password``, ``profile_key``, ``pni_identity_*``,
    ``signal_store_blob``) are base64 in JSON. The file is chmod 600.
    """

    model_config = ConfigDict(extra="ignore")

    schema_version: int = SCHEMA_VERSION
    environment: str = "live"

    number: str
    device_id: DeviceId
    aci: str
    pni: str
    password: str

    profile_key: B64Bytes | None = None
    master_key: B64Bytes | None = None
    storage_key: B64Bytes | None = None
    account_entropy_pool: str | None = None
    media_root_backup_key: B64Bytes | None = None

    # Raw bytes of the PNI identity keypair (libsignal serialization).
    # sigsig keeps these so it can regenerate / re-upload PNI prekeys on
    # demand without re-linking; there is no persistent PNI session state
    # in this MVP.
    pni_identity_key_pair: B64Bytes

    # Opaque libsignal protocol state for the ACI identity.
    # Generated by ``SignalStore.serialize()``; restored via
    # ``SignalStore.deserialize()``.
    signal_store_blob: B64Bytes

    @classmethod
    def from_json(cls, raw: str | bytes) -> Self:
        return cls.model_validate_json(raw)

    def to_json(self) -> str:
        return self.model_dump_json(indent=2, exclude_none=True)
